[package]
name = "parabel"
version = "0.0.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
pbr = "1.0"
log = "0.4"
simple_logger = "0.5"
time = "0.1"
rand = "0.6"
order-stat = "0.1"
assert_approx_eq = "1.0"
itertools = "0.7"
hashbrown = "0.1"

[build-dependencies]
cc = "1.0"
