[package]
name = "parabel"
version = "0.0.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[dependencies]
serde = { version = '1.0', features = ['derive'] }
bincode = "1.0"
pbr = "1.0"
log = "0.4"
simple_logger = "0.5"
time = "0.1"
rand = "0.6"
order-stat = "0.1"
assert_approx_eq = "1.0"
itertools = "0.7"
hashbrown = "0.1"
num-traits = "0.2"
bit-set = "0.5"
rayon = "1.0"
derive_builder = "0.7"
clap = {version = "2.32", features = ["yaml"]}

# A temporary fork with some customizations; hope to merge to upstream eventually
sprs = { git = "https://github.com/tomtung/sprs.git", branch = "master" }
# To stay consistent with sprs
ndarray = "0.11.2"
