[package]
name = "parabel_c-api"
version = "0.0.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[lib]
name = "parabel"
crate-type = ["staticlib", "cdylib"]

[dependencies]
itertools = "0.8"
libc = "0.2"
parabel = { version = "0", path = ".." }
rayon = "1.1"
simple_logger = "1.3"

[build-dependencies]
cbindgen = "0.9"

[profile.release]
panic = "abort"
